version: "3.9"

services:
  spark_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_app
    volumes:
      - ./data/raw:/app/data/raw
      - ./data/bronze:/app/data/bronze
      - ./data/silver:/app/data/silver
      - ./data/gold:/app/data/gold
      - ./scripts:/app/scripts
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
    tty: true